-- ============================================================
-- YETMANS BARBERSHOP — Migration 001
-- Backward-compatible: Eski randevular etkilenmez
-- Supabase Dashboard → SQL Editor → Yeni Query → Çalıştır
-- ============================================================

-- ── 1. STAFF TABLOSU ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS staff (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    role TEXT DEFAULT 'barber' CHECK (role IN ('master', 'apprentice', 'barber')),
    is_active BOOLEAN DEFAULT true NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);

-- RLS — Herkes okuyabilir, sadece service role yazabilir
ALTER TABLE staff ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read staff" ON staff FOR SELECT USING (true);

-- İlk personeli ekle (Ana Berber — mevcut randevuların sahibi olacak)
INSERT INTO staff (id, name, role, is_active)
VALUES (1, 'Ana Berber', 'master', true)
ON CONFLICT (id) DO NOTHING;

-- ── 2. APPOINTMENTS TABLOSUNA staff_id EKLE (BACKWARD COMPATIBLE) ──
-- Mevcut randevular NULL olarak kalacak veya default 1 alacak
ALTER TABLE appointments
    ADD COLUMN IF NOT EXISTS staff_id BIGINT REFERENCES staff(id) ON DELETE SET NULL DEFAULT 1;

-- Mevcut NULL'ları 1 (Ana Berber) yap — eski randevular bozulmaz
UPDATE appointments SET staff_id = 1 WHERE staff_id IS NULL;

-- ── 3. CUSTOM_SCHEDULES TABLOSU ─────────────────────────────
-- Belirli günler için standart mesaiyi ezip özelleştirmek için
CREATE TABLE IF NOT EXISTS custom_schedules (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date         DATE NOT NULL UNIQUE,      -- Hangi gün (Örn: 2025-06-15)
    is_closed    BOOLEAN DEFAULT false,     -- true → Tüm gün kapalı
    start_time   TIME,                      -- NULL = standart (10:00)
    end_time     TIME,                      -- NULL = standart (20:30)
    note         TEXT,                      -- Admin notu (Opsiyonel)
    created_at   TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()) NOT NULL
);

-- RLS
ALTER TABLE custom_schedules ENABLE ROW LEVEL SECURITY;
-- Herkes okuyabilir (available-slots endpoint kullanıyor)
CREATE POLICY "Public read custom_schedules" ON custom_schedules FOR SELECT USING (true);
-- Sadece authenticated (admin) yazabilir
CREATE POLICY "Auth write custom_schedules" ON custom_schedules
    FOR ALL USING (auth.role() = 'authenticated');

-- ── 4. İNDEXLER (Performans) ────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_appointments_date ON appointments (date);
CREATE INDEX IF NOT EXISTS idx_appointments_staff_id ON appointments (staff_id);
CREATE INDEX IF NOT EXISTS idx_appointments_status ON appointments (status);
CREATE INDEX IF NOT EXISTS idx_custom_schedules_date ON custom_schedules (date);

-- ============================================================
-- SONUÇ: 
--   ✅ Eski randevular staff_id=1 (Ana Berber) ile eşleştirildi
--   ✅ Yeni randevular staff_id seçerek kaydedilecek
--   ✅ custom_schedules tablosu oluşturuldu
-- ============================================================
